#############################################################################
# Experiment configurations
#############################################################################
energy: 65.351 #keV
detJ: [[1010.79405782, 1027.43844558]] #number of pixels
detK: [[2015.95118521, 2014.30163539]] #number of pixels
detL: [[4.53571404, 6.53571404]] #mm 
detRot: [[[89.48560133, 89.53313565, -0.50680978], [89.42516322, 89.22570012, -0.45511278]]]  #degree
detNJ: [2048, 2048, 2048, 2048]
detNK: [2048, 2048, 2048, 2048]
detPixelJ: [0.00148,0.00148,0.00148,0.00148] #mm
detPixelK: [0.00148,0.00148,0.00148,0.00148] #mm

Omega-Range: [ -90 , 90] #degree
NRot: 180
NDet: 2

reverseRot: true # for aero, is True, for rams: False



#############################################################################
# Configuration for material
#############################################################################

sample: 'gold'

#############################################################################
# Reconstruction parameters
#############################################################################

etalimit:  1.4137 # radian = 81 / 180.0 * np.pi
maxQ:       9
micsize: [20,20]
micVoxelSize: 0.01 #mm
micShift: [0,0,0]
micMask : None
searchBatchSize: 10000



#############################################################################
# Files and file path
#############################################################################

expdataNdigit: 6
fileBin: '../examples/johnson_aug18_demo/Au_reduced_1degree/Au_int_1degree_suter_aug18_z'
fileBinDigit: 6
fileBinDetIdx: [0,1]
fileBinLayerIdx: 0
_initialString: 'demo_gold_'


