BoundStart: 0.5
NIteration: 10
NSelect: 100
dReconParam: {}
detScale: 1
expansionStopHitRatio: 0.5
floodFillAccptThreshold: 0.85
floodFillNIteration: 2
floodFillNumberAngle: 1000
floodFillNumberVoxel: 20000
floodFillRandomRange: 0.005
floodFillSelectThreshold: 0.85
floodFillStartThreshold: 0.8
intensity_threshold: -1
postConvergeMisOrien: 0.001
postMisOrienThreshold: 0.02
postNIteration: 2
postNRandom: 50
postOriSeedWindow: 5
postRandomRange: 0.01
postThreshold: 0.3
postWindow: 3
searchBatchSize: 6000
